name=Arc32 Examples
version=1.0.0
author=Nishil Patel
maintainer=Nishil Patel
sentence=Example sketches for the Arc32 THEJAS32 RISC-V board.
paragraph=Includes Blink, SerialEcho, I2C Scanner.
category=Examples
url=https://github.com/nishil-26/arc32-sdk
architectures=riscv
includes=Arduino.h
